# Generated by Django 5.2.6 on 2025-11-14 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_perfil_lembrete_minutos_antes_and_more'),
        ('usuario', '0004_treino_exercicio'),
    ]

    operations = [
    ]
