# Generated by Django 5.2.6 on 2025-11-14 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_merge_20251114_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='treino',
            name='favorito',
            field=models.BooleanField(default=False),
        ),
    ]
