name: CI - Django Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Opcional: checagens rápidas de qualidade
      # - name: Lint (flake8)
      #   run: pip install flake8 && flake8 .

      - name: Django checks
        run: |
          python manage.py check
          python manage.py makemigrations --check --dry-run

      - name: Run tests
        run: |
          python manage.py test -v 2

